export const theme = {
    "--ck-font-family": "SF Pro Rounded",
    "--ck-border-radius": "10px",
    "--ck-connectbutton-font-size": "17px",
    "--ck-connectbutton-color": "var(--text)",
    "--ck-connectbutton-background": "var(--bw)",
    "--ck-connectbutton-border-radius": "10px",
    "--ck-connectbutton-hover-background": "var(--main)",
    "--ck-connectbutton-balance-color": "var(--text)",
    "--ck-connectbutton-balance-background": "var(--bg)",
    "--ck-connectbutton-balance-hover-background": "#d5cde6",
    "--ck-connectbutton-balance-connectbutton-border-radius": "0px 10px 10px 0",
    "--ck-primary-button-color": "var(--text)",
    "--ck-primary-button-background": "var(--bw)",
    "--ck-primary-button-border-radius": "10px",
    "--ck-primary-button-hover-background": "var(--main)",
    "--ck-secondary-button-border-radius": "10px",
    "--ck-secondary-button-color": "var(--text)",
    "--ck-secondary-button-background": "var(--bw)",
    "--ck-secondary-button-hover-background": "var(--main)",
    "--ck-focus-color": "#3B99FC",
    "--ck-overlay-background": "var(--overlay)",
    "--ck-body-color": "var(--text)",
    "--ck-body-color-muted": "rgba(0, 0, 0, 0.5)",
    "--ck-body-background": "var(--bg)",
    "--ck-body-background-transparent": "rgba(255,255,255,0)",
    "--ck-body-background-secondary": "rgba(0,0,0,0.1)",
    "--ck-body-background-secondary-hover-background": "#4D4D4D",
    "--ck-body-background-secondary-hover-outline": "var(--text)",
    "--ck-body-background-tertiary": "var(--bw)",
    "--ck-tertiary-border-radius": "10px",
    "--ck-body-action-color": "var(--text)",
    "--ck-body-color-danger": "#FF4E4E",
    "--ck-body-disclaimer-background": "#d9cde7",
    "--ck-body-disclaimer-font-weight": "500",
    "--ck-body-disclaimer-color": "#888079",
    "--ck-body-disclaimer-link-color": "#5B5650",
    "--ck-tooltip-border-radius": "10px",
    "--ck-tooltip-color": "var(--text)",
    "--ck-tooltip-background": "var(--bw)",
    "--ck-tooltip-background-secondary": "#d9cde7",
    "--ck-spinner-color": "#1A88F8",
    "--ck-dropdown-button-color": "var(--text)",
    "--ck-dropdown-button-background": "var(--bw)",
    "--ck-dropdown-button-hover-background": "var(--main)",
    "--ck-dropdown-pending-color": "rgba(0, 0, 0, 0.5)",
    "--ck-dropdown-active-color": "var(--blank)",
    "--ck-dropdown-active-static-color": "rgba(0, 0, 0, 0.5)",
    "--ck-dropdown-active-background": "#3B99FC",
    "--ck-dropdown-active-border-radius": "10px",
    "--ck-dropdown-color": "rgba(0, 0, 0, 0.5)",
    "--ck-dropdown-background": "var(--bw)",
    "--ck-dropdown-border-radius": "10px",
    "--ck-alert-color": "rgba(0, 0, 0, 0.5)",
    "--ck-alert-background": "#F5F5F5",
    "--ck-alert-border-radius": "10px",
    "--ck-qr-border-radius": "10px",
    "--ck-qr-background": "var(--bw)",
    "--ck-recent-badge-border-radius": "32px",
    "--ck-recent-badge-box-shadow": "inset 0 0 0 2px currentColor",
    "--ck-graphic-primary-color": "var(--border)",
    "--ck-graphic-primary-background": "var(--bw)",
    "--ck-graphic-compass-background": "var(--bw)",
    "--ck-siwe-border": "#8E8985",

    "--ck-connectbutton-box-shadow": "4px 4px 0px #B620E0, inset 0 0 0 2px #B620E0",
    "--ck-connectbutton-active-box-shadow": "inset 0 0 0 2px #B620E0",
    "--ck-connectbutton-balance-box-shadow": "4px 4px 0px #B620E0, inset 0 0 0 2px #B620E0",
    "--ck-connectbutton-balance-connectbutton-box-shadow": "4px 8px 0px -4px #B620E0, inset 0 0 0 2px #B620E0",

    "--ck-primary-button-box-shadow": "inset 0 0 0 2px #B620E0, 4px 4px 0 0 #B620E0",
    "--ck-primary-button-hover-box-shadow": "inset 0 0 0 2px #B620E0, 4px 4px 0 0 #B620E0",

    "--ck-secondary-button-box-shadow": "4px 4px 0 0 #B620E0, inset 0 0 0 2px #B620E0",

    "--ck-tertiary-box-shadow": "4px 4px 0 0 #B620E0, inset 0 0 0 2px #B620E0",
    "--ck-body-disclaimer-box-shadow": "4px 4px 0 0 #B620E0, inset 2px 0 0 0 #B620E0, inset -2px 0 0 0 #B620E0, inset 0 -2px 0 0 #B620E0",

    "--ck-modal-box-shadow": "10px 10px 0px #B620E0, inset 0 0 0 2px #B620E0",
    "--ck-tooltip-shadow": "6px 6px 0 0 #B620E0, 0 0 0 2px #B620E0",
    "--ck-dropdown-button-box-shadow": "2px 2px 0 2px #B620E0,  0 0 0 2px #B620E0",
    "--ck-dropdown-button-hover-box-shadow": "2px 2px 0 0 #B620E0,  0 0 0 2px #B620E0",
    "--ck-dropdown-active-box-shadow": "inset 0 0 0 2px #B620E0",
    "--ck-dropdown-box-shadow": "4px 4px 0 0 #B620E0, inset 0 0 0 2px #B620E0",
    "--ck-qr-border-color": "#B620E0",
    "--ck-qr-dot-color": "#B620E0",
    "--ck-copytoclipboard-stroke": "#B620E0",
    "--ck-body-divider": "#B620E0",
    "--ck-body-color-muted-hover": "#B620E0",
    "--ck-body-disclaimer-link-hover-color": "#B620E0",

};
